# Generated by Django 3.0.5 on 2020-04-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Complete name of the author.', max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Book's title.", max_length=250)),
                ('edition', models.PositiveSmallIntegerField(help_text="Number of book's edition.")),
                ('publication_year', models.PositiveSmallIntegerField(db_index=True, help_text='Year of the publication date.')),
                ('authors', models.ManyToManyField(help_text="Book's authors, there may be more than one.", related_name='books', to='books.Author')),
            ],
            options={
                'ordering': ['-publication_year', 'name'],
            },
        ),
    ]
